name: demo
description: Demo
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  device_info_plus: ^9.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  get_it: ^7.6.7
  hydrated_bloc: ^9.1.3
  injectable: ^2.3.2
  intl: ^0.18.0
  lottie: ^3.0.0
  nfc_reader_data:
    path: ../../packages/nfc_reader_data
  nfc_reader_domain:
    path: ../../packages/nfc_reader_domain
  nfc_reader_presentation:
    path: ../../packages/nfc_reader_presentation
  path_provider: ^2.1.2

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.8
  change_app_package_name: ^1.1.0
  flutter_gen_runner: ^5.4.0
  flutter_native_splash: ^2.3.10
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.7
  import_sorter: ^4.6.0
  injectable_generator: ^2.4.1
  mocktail: ^1.0.0
  rename_app: ^1.3.2
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/

flutter_gen:
  output: lib/app/assets
  integrations:
    flutter_svg: true
    lottie: true
