name: nfc_card_data
description: Data layer package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.0.0
  flutter:
    sdk: flutter
  nfc_card_domain:
    path: ../nfc_card_domain
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.7.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0

dev_dependencies:
  build_runner: ^2.3.2
  import_sorter: ^4.6.0
  json_serializable: ^6.5.4
  mocktail: ^1.0.3
  retrofit_generator: ^8.1.0
  very_good_analysis: ^5.1.0
